name: CI
on:
    push:
        branches: [master]
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
              with:
                  persist-credentials: false
            - run: npm i
            - run: git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/maximedupre/maximedupre.com.git
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - run: npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
            - run: ls && ls dist && ls node_modules
