name: CI
on:
    push:
        branches: [master]
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
              with:
                  persist-credentials: false
            - run: npm i
            - run: git config --global user.name "Maxime Dupré"
            - run: git config --global user.email "maximedupre@me.com"
            - run: npm run deploy
